### ISSUE TITLE
Float to String Support

### ISSUE THREAD

**Issue by KyleMercer** [sblyolcubal/arduino-iot2000#1]
Suggest adding support for conversion of floating point variables to strings. AVR based Arduino devices use the dtostrf() function.

Source exists on GitHub for Galileo implementation for dtostrf() function. See:
https://github.com/01org/corelibs-galileo/tree/master/cores/arduino/avr

**Comment by sblyolcubal** [comment]
Hi,
this board support for IOT2000 are forked from https://github.com/01org/corelibs-galileo/.
Therefore the files are same. Did I not understand your suggestion ?

**Comment by KyleMercer** [comment]
I am not sure what to say. I had to manually create and declare the dtostrf() function within my arduino sketch created for the IOT2000 in order to use the function. I could not call dtostrf() directly without getting a compiler error.

**Comment by sblyolcubal** [comment]
Hi,
look here:
https://communities.intel.com/thread/75830

But you don't need **dtostrf()**.

For format floating number:

`char sout[100];
sprintf(sout, "%d.%df", 5, 2, 35.5);
`
